# Generated by Django 4.1.2 on 2022-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humidity", models.FloatField()),
                ("temperature", models.FloatField()),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
